# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: glossary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x11\n\x0fGetTermsRequest\"9\n\x10GetTermsResponse\x12%\n\x05terms\x18\x01 \x03(\x0b\x32\x16.glossary.TermResponse\"!\n\x0eGetTermRequest\x12\x0f\n\x07term_id\x18\x01 \x01(\x05\"p\n\x0cTermResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x10\n\x08relation\x18\x05 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\"i\n\x11\x43reateTermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\x12\x10\n\x08relation\x18\x04 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\"z\n\x11UpdateTermRequest\x12\x0f\n\x07term_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x10\n\x08relation\x18\x05 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\"$\n\x11\x44\x65leteTermRequest\x12\x0f\n\x07term_id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteTermResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe0\x02\n\x0fGlossaryService\x12\x41\n\x08GetTerms\x12\x19.glossary.GetTermsRequest\x1a\x1a.glossary.GetTermsResponse\x12;\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nCreateTerm\x12\x1b.glossary.CreateTermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x16.glossary.TermResponse\x12G\n\nDeleteTerm\x12\x1b.glossary.DeleteTermRequest\x1a\x1c.glossary.DeleteTermResponseb\x06proto3')



_GETTERMSREQUEST = DESCRIPTOR.message_types_by_name['GetTermsRequest']
_GETTERMSRESPONSE = DESCRIPTOR.message_types_by_name['GetTermsResponse']
_GETTERMREQUEST = DESCRIPTOR.message_types_by_name['GetTermRequest']
_TERMRESPONSE = DESCRIPTOR.message_types_by_name['TermResponse']
_CREATETERMREQUEST = DESCRIPTOR.message_types_by_name['CreateTermRequest']
_UPDATETERMREQUEST = DESCRIPTOR.message_types_by_name['UpdateTermRequest']
_DELETETERMREQUEST = DESCRIPTOR.message_types_by_name['DeleteTermRequest']
_DELETETERMRESPONSE = DESCRIPTOR.message_types_by_name['DeleteTermResponse']
GetTermsRequest = _reflection.GeneratedProtocolMessageType('GetTermsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTERMSREQUEST,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.GetTermsRequest)
  })
_sym_db.RegisterMessage(GetTermsRequest)

GetTermsResponse = _reflection.GeneratedProtocolMessageType('GetTermsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTERMSRESPONSE,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.GetTermsResponse)
  })
_sym_db.RegisterMessage(GetTermsResponse)

GetTermRequest = _reflection.GeneratedProtocolMessageType('GetTermRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTERMREQUEST,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.GetTermRequest)
  })
_sym_db.RegisterMessage(GetTermRequest)

TermResponse = _reflection.GeneratedProtocolMessageType('TermResponse', (_message.Message,), {
  'DESCRIPTOR' : _TERMRESPONSE,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.TermResponse)
  })
_sym_db.RegisterMessage(TermResponse)

CreateTermRequest = _reflection.GeneratedProtocolMessageType('CreateTermRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETERMREQUEST,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.CreateTermRequest)
  })
_sym_db.RegisterMessage(CreateTermRequest)

UpdateTermRequest = _reflection.GeneratedProtocolMessageType('UpdateTermRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETERMREQUEST,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.UpdateTermRequest)
  })
_sym_db.RegisterMessage(UpdateTermRequest)

DeleteTermRequest = _reflection.GeneratedProtocolMessageType('DeleteTermRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETETERMREQUEST,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.DeleteTermRequest)
  })
_sym_db.RegisterMessage(DeleteTermRequest)

DeleteTermResponse = _reflection.GeneratedProtocolMessageType('DeleteTermResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETETERMRESPONSE,
  '__module__' : 'glossary_pb2'
  # @@protoc_insertion_point(class_scope:glossary.DeleteTermResponse)
  })
_sym_db.RegisterMessage(DeleteTermResponse)

_GLOSSARYSERVICE = DESCRIPTOR.services_by_name['GlossaryService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTERMSREQUEST._serialized_start=28
  _GETTERMSREQUEST._serialized_end=45
  _GETTERMSRESPONSE._serialized_start=47
  _GETTERMSRESPONSE._serialized_end=104
  _GETTERMREQUEST._serialized_start=106
  _GETTERMREQUEST._serialized_end=139
  _TERMRESPONSE._serialized_start=141
  _TERMRESPONSE._serialized_end=253
  _CREATETERMREQUEST._serialized_start=255
  _CREATETERMREQUEST._serialized_end=360
  _UPDATETERMREQUEST._serialized_start=362
  _UPDATETERMREQUEST._serialized_end=484
  _DELETETERMREQUEST._serialized_start=486
  _DELETETERMREQUEST._serialized_end=522
  _DELETETERMRESPONSE._serialized_start=524
  _DELETETERMRESPONSE._serialized_end=561
  _GLOSSARYSERVICE._serialized_start=564
  _GLOSSARYSERVICE._serialized_end=916
# @@protoc_insertion_point(module_scope)
